[package]
name = "png-secret"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "A simple steganography tool for PNG images"

[dependencies]
anyhow = "1.0"
crc = "3.2.1"
thiserror = "1.0"
